package jena.examples.vocabulary;

/* CVS $Id: $ */

import com.hp.hpl.jena.rdf.model.*;

/**
 * Vocabulary definitions from RDA2.rdf
 * 
 * @author Auto-generated by schemagen on 12 9 2014 14:25
 */
public class RDA2 {
	/**
	 * <p>
	 * The RDF model that holds the vocabulary terms
	 * </p>
	 */
	private static Model m_model = ModelFactory.createDefaultModel();

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 */
	public static final String NS = "http://rdvocab.info/ElementsGr2/";

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 * 
	 * @see #NS
	 */
	public static String getURI() {
		return NS;
	}

	/**
	 * <p>
	 * The namespace of the vocabulary as a resource
	 * </p>
	 */
	public static final Resource NAMESPACE = m_model.createResource(NS);

	public static final Property addressOfTheCorporateBody = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/addressOfTheCorporateBody");

	public static final Property addressOfThePerson = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/addressOfThePerson");

	public static final Property affiliation = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/affiliation");

	public static final Property associatedInstitution = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/associatedInstitution");

	public static final Property biographicalInformation = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/biographicalInformation");

	public static final Property corporateHistory = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/corporateHistory");

	public static final Property countryAssociatedWithThePerson = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/countryAssociatedWithThePerson");

	public static final Property dateAssociatedWithTheCorporateBody = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/dateAssociatedWithTheCorporateBody");

	public static final Property dateAssociatedWithTheFamily = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/dateAssociatedWithTheFamily");

	public static final Property dateAssociatedWithThePerson = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/dateAssociatedWithThePerson");

	public static final Property dateOfBirth = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/dateOfBirth");

	public static final Property dateOfConferenceEtc = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/dateOfConferenceEtc");

	public static final Property dateOfDeath = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/dateOfDeath");

	public static final Property dateOfEstablishment = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/dateOfEstablishment");

	public static final Property dateOfTermination = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/dateOfTermination");

	public static final Property dateOfUsage = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/dateOfUsage");

	public static final Property familyHistory = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/familyHistory");

	public static final Property fieldOfActivityOfTheCorporateBody = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/fieldOfActivityOfTheCorporateBody");

	public static final Property fieldOfActivityOfThePerson = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/fieldOfActivityOfThePerson");

	public static final Property fullerFormOfName = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/fullerFormOfName");

	public static final Property fullerFormOfNamePerson = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/fullerFormOfNamePerson");

	public static final Property gender = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/gender");

	public static final Property hereditaryTitle = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/hereditaryTitle");

	public static final Property identifierForTheCorporateBody = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/identifierForTheCorporateBody");

	public static final Property identifierForTheFamily = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/identifierForTheFamily");

	public static final Property identifierForThePerson = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/identifierForThePerson");

	public static final Property languageOfTheCorporateBody = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/languageOfTheCorporateBody");

	public static final Property languageOfThePerson = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/languageOfThePerson");

	public static final Property locationOfConferenceEtc = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/locationOfConferenceEtc");

	public static final Property locationOfHeadquarters = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/locationOfHeadquarters");

	public static final Property name = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/name");

	public static final Property nameOfTheCorporateBody = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/nameOfTheCorporateBody");

	public static final Property nameOfTheFamily = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/nameOfTheFamily");

	public static final Property nameOfThePerson = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/nameOfThePerson");

	public static final Property note = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/note");

	public static final Property numberOfAConferenceEtc = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/numberOfAConferenceEtc");

	public static final Property otherDesignationAssociatedWithTheCorporateBody = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/otherDesignationAssociatedWithTheCorporateBody");

	public static final Property otherDesignationAssociatedWithThePerson = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/otherDesignationAssociatedWithThePerson");

	public static final Property periodOfActivityOfThePerson = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/periodOfActivityOfThePerson");

	public static final Property placeAssociatedWithTheCorporateBody = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/placeAssociatedWithTheCorporateBody");

	public static final Property placeAssociatedWithTheFamily = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/placeAssociatedWithTheFamily");

	public static final Property placeOfBirth = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/placeOfBirth");

	public static final Property placeOfDeath = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/placeOfDeath");

	public static final Property placeOfResidence = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/placeOfResidence");

	public static final Property preferredNameForTheCorporateBody = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/preferredNameForTheCorporateBody");

	public static final Property preferredNameForTheFamily = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/preferredNameForTheFamily");

	public static final Property preferredNameForThePerson = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/preferredNameForThePerson");

	public static final Property professionOrOccupation = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/professionOrOccupation");

	public static final Property prominentMemberOfTheFamily = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/prominentMemberOfTheFamily");

	public static final Property scopeOfUsage = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/scopeOfUsage");

	public static final Property titleOfThePerson = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/titleOfThePerson");

	public static final Property typeOfFamily = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/typeOfFamily");

	public static final Property undifferentiatedNameIndicator = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/undifferentiatedNameIndicator");

	public static final Property undifferentiatedNameIndicatorCorporateBody = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/undifferentiatedNameIndicatorCorporateBody");

	public static final Property undifferentiatedNameIndicatorFamily = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/undifferentiatedNameIndicatorFamily");

	public static final Property undifferentiatedNameIndicatorPerson = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/undifferentiatedNameIndicatorPerson");

	public static final Property variantNameForTheCorporateBody = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/variantNameForTheCorporateBody");

	public static final Property variantNameForTheFamily = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/variantNameForTheFamily");

	public static final Property variantNameForThePerson = m_model
			.createProperty("http://rdvocab.info/ElementsGr2/variantNameForThePerson");

}
